[package]
name = "vapor-forge-audit-loader"
version = "0.1.0"
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
name = "vapor_forge"
crate-type = ["cdylib"]

[target.'cfg(target_os = "linux")'.dependencies]
libc.workspace = true
once_cell.workspace = true
vapor-forge-core = { path = "../runtime-core" }
vapor-forge-diagnostics = { path = "../diagnostics" }
vapor-forge-hooks = { path = "../hooks" }
vapor-forge-memory = { path = "../memory" }
tracing.workspace = true
