[package]
name = "vapor-forge-proton-inject"
version = "0.1.0"
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
name = "vapor_forge_proton_inject"
crate-type = ["cdylib"]

[target.'cfg(all(target_os = "linux", target_pointer_width = "64"))'.dependencies]
vapor-forge-inject-protocol = { path = "../inject-protocol" }
vapor-forge-pe = { path = "../pe" }
libc.workspace = true
