[package]
name = "vapor-forge-features"
version = "0.1.0"
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
prost.workspace = true
vapor-forge-abi = { path = "../steam-abi" }
vapor-forge-config = { path = "../config" }
vapor-forge-diagnostics = { path = "../diagnostics" }
vapor-forge-scripting = { path = "../scripting" }
tracing.workspace = true
ureq.workspace = true
