[package]
name = "vapor-forge-features"
version = "0.1.0"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
autobins = false

[features]
default = []
tools = []

[[bin]]
name = "vapor-forge-ticket-tool"
path = "src/bin/vapor-forge-ticket-tool.rs"
required-features = ["tools"]

[dependencies]
prost.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
vapor-forge-steam-protocol = { path = "../steam-protocol" }
vapor-forge-cloud-core = { path = "../cloud-core" }
vapor-forge-cloud-cumulus = { path = "../cloud-cumulus" }
vapor-forge-cloud-local = { path = "../cloud-local" }
vapor-forge-config = { path = "../config" }
vapor-forge-core = { path = "../runtime-core" }
vapor-forge-sync-state = { path = "../sync-state" }
tracing.workspace = true
ureq.workspace = true

[dev-dependencies]
tempfile = "3"
